# The default path. If this is specified and no path is passed to Wadinator, this will be used. This defaults to "".
default-path = ""

# The default recursion setting. If this is set to true, paths will be read recursively by default. This can be
# overridden by passing the -recurse or -no-recurse parameters. This defaults to false.
default-recurse = false

# If this is set to true, the Wadinator "played" file will be read and written to. If this is set to false, the
# "played" file will be ignored. This defaults to true.
log-rng-results = true

# If this is set to true, Wadinator will assume that all input WADs are Heretic WADs. This can be overridden using
# the -doom switch. This defaults to false.
use-heretic = false

# The setting that controls the text file finder's output. If this is set to true, the found text file associated with
# a WAD will be printed into the console. Otherwise, it will output a command to open it in a given text editor, which
# can be customised in the [text.editor] section below.
print-contents = false

# Text editor settings.
[text.editor]

# The path to the editor's executable.
filename = "vim"


# Doom-specific settings.
[games.doom]

# The path to the game's executable.
filename = "dsda-doom"

# The specified port uses complevels. This should be set to true for Doom source ports based on PrBoom (PrBoom,
# PrBoom+, dsda-doom, etc.) and false for others. This setting will be ignored for Heretic.
uses-complevels = true


# Heretic-specific settings.
[games.heretic]

# The path to the game's executable.
filename = "crispy-heretic"

# The specified port uses complevels. This should be set to true for Doom source ports based on PrBoom (PrBoom,
# PrBoom+, dsda-doom, etc.) and false for others. This setting will be ignored for Heretic.
uses-complevels = false
